name: release

on:
  release: # Docs: <https://git.io/JeBz1#release-event-release>
    types: [published]

jobs:
  build:
    name: Build for ${{ matrix.os }} (${{ matrix.arch }})
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        os: [linux, windows, freebsd]
        arch: [386, amd64, arm, arm64]
        include:
          - os: darwin
            arch: amd64
          - os: darwin
            arch: arm64
    steps:
      - uses: actions/setup-go@v2
        with: {go-version: 1.17}

      - uses: actions/checkout@v2

      - uses: gacts/github-slug@v1
        id: slug

      - name: Generate builder values
        id: values
        run: echo "::set-output name=binary-name::stoppropaganda_v${{ steps.slug.outputs.version }}_${{ matrix.os }}_${{ matrix.arch }}"

      - name: Build application
        env:
          GOOS: ${{ matrix.os }}
          GOARCH: ${{ matrix.arch }}
          CGO_ENABLED: 0
          LDFLAGS: -s -w
        run: go build -trimpath -ldflags "$LDFLAGS" -o "./${{ steps.values.outputs.binary-name }}" ./cmd/stoppropaganda/

      - name: Upload binary file to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ steps.values.outputs.binary-name }}
          asset_name: ${{ steps.values.outputs.binary-name }}
          tag: ${{ github.ref }}

  docker-image:
    name: Build docker image
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - uses: gacts/github-slug@v1
        id: slug

      - uses: docker/setup-qemu-action@v1 # Action page: <https://github.com/docker/setup-qemu-action>

      - uses: docker/setup-buildx-action@v1 # Action page: <https://github.com/docker/setup-buildx-action>

      - uses: docker/login-action@v1 # Action page: <https://github.com/docker/login-action>
        with:
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - uses: docker/login-action@v1 # Action page: <https://github.com/docker/login-action>
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v2 # Action page: <https://github.com/docker/build-push-action>
        with:
          context: .
          file: Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64,linux/ppc64le,linux/386,linux/arm/v7,linux/arm/v6
          build-args: "APP_VERSION=${{ steps.slug.outputs.version }}"
          tags: |
            ghcr.io/${{ github.actor }}/${{ github.event.repository.name }}:${{ steps.slug.outputs.version }}
            ghcr.io/${{ github.actor }}/${{ github.event.repository.name }}:latest
            erkexzcx/stoppropaganda:${{ steps.slug.outputs.version }}
            erkexzcx/stoppropaganda:latest
